### ISSUE TITLE
Importing the project into Eclipse generates an error

### ISSUE THREAD

**Issue by inahas** [mstahv/watson-java-api#1]
The import maven project in Eclipse complains about vwscdn,

Screenshot attached.

<img width="752" alt="screen shot 2015-11-18 at 7 52 56 pm" src="https://cloud.githubusercontent.com/assets/7094874/11260214/ab350b84-8e2e-11e5-9323-1ce174efec30.png">

**Comment by mstahv** [comment]
Yep, Eclipse and its "Maven support" :-) I upgrade that plugin to newer version in https://github.com/mstahv/watson-java-api/commit/d116421009db514691c7e4fb54845389addc3f3c . It should now behave better with Eclipse as the maven plugin has some Eclipse specific hints built in.
